### ISSUE TITLE
Blocks claims it is giving up retrying, but keeps going

### ISSUE THREAD

**Issue by mattdodge** [nio-blocks/socketio#8]
This gets spit out in the logs:

```
Failed to reconnect after unexpected close. Giving up.
```

But the block seems to continue its back-off retry strategy

**Comment by oleiman** [comment]
I can't seem to reproduce this issue. I say we wait until it happens again in order to get a better sense of the precise failure conditions.

**Comment by mattdodge** [comment]
Closed by #17
